site_name: Google Docs guide
site_author: Anastasiya Fomina

nav:
  - About This Guide: index.md
  - Managing documents: 
    - Create documents: src/managing/create.md
    - Download documents: src/managing/download.md
    - Print documents: src/managing/print.md
    - Manage access: src/managing/access.md
    - Manage page settings: src/managing/page settings.md
    - Format the text: src/managing/format text.md
    - Insert content: src/managing/insert content.md 
    - Manage add-ons:  src/managing/manage add-ons.md 

      

theme:
  name: material
  logo: 'src/img/logo.png'
  feature:
    tabs: false
  language: 'en'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.extra
  - pymdownx.snippets:
      base_path: docs/src
    
plugins:
  - search

extra_css:
  - 'stylesheets/extra-page-content.css'
  - 'https://use.fontawesome.com/releases/v5.7.0/css/all.css'
  - 'https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css'
  
